[tool.poetry]
name = "play-battlesnake-in-discord"
version = "0.1.0"
description = ""
authors = ["mdhexdrive <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
